Atualização automática

diff --git a/.github/workflows/build_and_test.yml b/.github/workflows/build_and_test.yml
--- a/.github/workflows/build_and_test.yml
+++ b/.github/workflows/build_and_test.yml
@@ -18,8 +18,16 @@ jobs:
     - name: Install dependencies
       run: |
         sudo apt-get update
-        sudo apt-get install -y cmake ninja-build build-essential
-        sudo apt-get install -y liblua5.3-0 libglm-dev libglfw3 libassimp-dev libfreeimage-dev rapidjson-dev libbullet-dev libfreetype6-dev
+        sudo apt-get install -y \
+        cmake ninja-build build-essential \
+        liblua5.3-0 libglm-dev libglfw3 libassimp-dev libfreeimage-dev rapidjson-dev libbullet-dev libfreetype6-dev
+
 
     - name: Run tests
       run: ./scripts/run_tests.sh
+
+    - name: Check Lua installation
+      run: |
+        lua -v || echo "Lua not found"i
+        ls /usr/include/lua5.4/ || echo "Headers not found"
+        ls /usr/lib/x86_64-linux-gnu/liblua5.4.* || echo "Libraries not found"
